version: 0.0
os: linux
files:
  - source: /
    destination: /opt/twig-app
    overwrite: yes

permissions:
  - object: /opt/twig-app
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755

hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/application-start.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/application-stop.sh
      timeout: 300
      runas: root
