version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Installing Maven..."
      - sudo amazon-linux-extras install maven2 -y
      - mvn --version # Verify Maven installation
  build:
    commands:
      - echo "Building the application..."
      - mvn clean package
  post_build:
    commands:
      - echo "Build completed."

artifacts:
  files:
    - target/*.war
    - appspec.yml
    - scripts/**/*
    - Dockerfile
  discard-paths: no
