version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto21
  build:
    commands:
      - mvn clean package
      - docker build -t twig-app .
      - docker save twig-app > twig-app.tar
artifacts:
  files:
    - '**/*'
  base-directory: 'target'
