version: 0.2
phases:
  install:
    commands:
      # Install Java 21 manually since CodeBuild doesn't have it pre-installed
      - wget https://corretto.aws/downloads/latest/amazon-corretto-21-x64-linux-jdk.tar.gz
      - tar xzf amazon-corretto-21-x64-linux-jdk.tar.gz
      - export JAVA_HOME=$PWD/amazon-corretto-21.0.1.12.1-linux-x64
      - export PATH=$JAVA_HOME/bin:$PATH
      - java -version
      - mvn -v
  pre_build:
    commands:
      - mvn clean
  build:
    commands:
      - mvn package
  post_build:
    commands:
      - echo "Build artifacts:"
      - ls -la target/
artifacts:
  files:
    - 'target/twig-*-core.jar'
  base-directory: '.'
