version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to CodeBuild environment...
      - docker version  # Check Docker is already running
  build:
    commands:
      - echo Building WAR file...
      - mvn clean package -Drevision=0.0.4
      - echo Building Docker image...
      - docker build -t twig-tomcat .
  post_build:
    commands:
      - echo "Ready to deploy"
artifacts:
  files:
    - appspec.yml
    - scripts/start_container.sh
