version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      docker: 20
    commands:
      - echo Installing Maven...
      - yum install -y maven
  build:
    commands:
      - echo Building shaded JAR...
      - mvn clean package -DskipTests
      - echo Building Docker image...
      - docker build -t twig-app .
  post_build:
    commands:
      - echo Build complete.

artifacts:
  files:
    - target/twig-0.0.4-core.jar
