version: 0.0
os: linux

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven
      - yum install -y maven
  build:
    commands:
      - echo Building the Java application
      - mvn clean package
      - ls -l target/  # This will list the contents of the target directory to help debug
  post_build:
    commands:
      - echo Build completed successfully!
artifacts:
  files:
    - target/*.war  # This assumes the WAR file is generated in the target folder; adjust if necessary
