version: 0.2
phases:
  install:
    commands:
      - wget https://corretto.aws/downloads/latest/amazon-corretto-21-x64-linux-jdk.tar.gz
      - tar xzf amazon-corretto-21-x64-linux-jdk.tar.gz
      - export JAVA_HOME=$PWD/amazon-corretto-21.0.1.12.1-linux-x64
      - export PATH=$JAVA_HOME/bin:$PATH
  build:
    commands:
      - mvn clean package
      - docker build -t twig-app .
      - docker save twig-app > twig-app.tar
artifacts:
  files:
    - '**/*'
  base-directory: 'target'
