version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies
  build:
    commands:
      - echo Building application

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - Dockerfile
    - target/*.war
  discard-paths: no
  base-directory: twig.war
