version: 0.2

phases:
  pre_build:
    commands:
      - echo Setting up Docker...
      - sudo yum update -y
      - sudo yum install -y docker
      - sudo service docker start
      - sudo usermod -aG docker ec2-user
  build:
    commands:
      - echo Building WAR file...
      - mvn clean package -Drevision=0.0.4
      - echo Building Docker image...
      - docker build -t twig-tomcat .
  post_build:
    commands:
      - echo Uploading Docker image to EC2...
      - scp -i <path-to-your-ec2-key> -o StrictHostKeyChecking=no target/twig-0.0.4.war ec2-user@<your-ec2-ip>:/home/ec2-user/twig-0.0.4.war
      - ssh -i <path-to-your-ec2-key> -o StrictHostKeyChecking=no ec2-user@<your-ec2-ip> 'bash /home/ec2-user/scripts/start_container.sh'
artifacts:
  files:
    - appspec.yml
    - scripts/start_container.sh
