version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo Installing dependencies...
      - mvn --version
  pre_build:
    commands:
      - echo Checking Docker availability...
      - docker --version
  build:
    commands:
      - echo Building Java project with Maven...
      - mvn clean package -Drevision=0.0.4 -X  # Enables full Maven logs for debugging
      - echo Building Docker image...
      - docker build -t twig-tomcat .
  post_build:
    commands:
      - echo Build completed successfully.
      - echo You can now deploy this to your EC2 instance running Tomcat.

artifacts:
  files:
    - target/*.jar
    - target/*.war
    - Dockerfile
    - appspec.yml
    - scripts/start_container.sh
