version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Installing Maven..."
      - wget https://dlcdn.apache.org/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.tar.gz
      - tar -xvf apache-maven-3.8.6-bin.tar.gz -C /opt
      - ln -s /opt/apache-maven-3.8.6 /opt/maven
      - export MAVEN_HOME=/opt/maven
      - export PATH=$PATH:$MAVEN_HOME/bin
      - echo "Maven and Java installed."
      - mvn --version # Verify installation

  post_build:
    commands:
      - echo "Build completed."

artifacts:
  files:
    - target/*.war
    - appspec.yml
    - scripts/**/*
    - Dockerfile
  discard-paths: no
