version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - mvn clean package
      - docker build -t twig-app .
  post_build:
    commands:
      - echo "Build completed on $(date)"
artifacts:
  files:
    - target/twig-*.jar
    - Dockerfile
