version: 0.2
phases:
  install:
    commands:
      # Install Java 21
      - wget https://corretto.aws/downloads/latest/amazon-corretto-21-x64-linux-jdk.tar.gz
      - tar xzf amazon-corretto-21-x64-linux-jdk.tar.gz -C /usr/local
      - export JAVA_HOME=/usr/local/amazon-corretto-21.0.1.12.1-linux-x64
      - export PATH=$JAVA_HOME/bin:$PATH
      
      # Install Maven
      - wget https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz
      - tar xzf apache-maven-3.9.6-bin.tar.gz -C /usr/local
      - export PATH=/usr/local/apache-maven-3.9.6/bin:$PATH
      
      # Verify installations
      - java -version
      - mvn -v

  build:
    commands:
      - mvn clean package

artifacts:
  files:
    - 'target/*.jar'
