version: 0.2
phases:
  install:
    commands:
      # Install Java 21
      - wget https://corretto.aws/downloads/latest/amazon-corretto-21-x64-linux-jdk.tar.gz
      - tar xzf amazon-corretto-21-x64-linux-jdk.tar.gz
      - export JAVA_HOME=$PWD/amazon-corretto-21.0.1.12.1-linux-x64
      - export PATH=$JAVA_HOME/bin:$PATH
      
      # Install Maven
      - wget https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz
      - tar xzf apache-maven-3.9.6-bin.tar.gz
      - export M2_HOME=$PWD/apache-maven-3.9.6
      - export PATH=$M2_HOME/bin:$PATH
      
      # Verify installations
      - java -version
      - mvn -version
      
  pre_build:
    commands:
      - mvn clean
  build:
    commands:
      - mvn package
  post_build:
    commands:
      - echo "Build artifacts:"
      - ls -la target/
artifacts:
  files:
    - 'target/twig-*-core.jar'
  base-directory: '.'
