version: 0.2
phases:
  install:
    commands:
      # 1. Install Java 21
      - echo "Installing Amazon Corretto 21..."
      - wget -q https://corretto.aws/downloads/latest/amazon-corretto-21-x64-linux-jdk.tar.gz
      - mkdir -p /usr/local/java
      - tar xzf amazon-corretto-21-x64-linux-jdk.tar.gz -C /usr/local/java
      - export JAVA_HOME=/usr/local/java/amazon-corretto-21.0.1.12.1-linux-x64
      - export PATH=$JAVA_HOME/bin:$PATH
      
      # 2. Install Maven
      - echo "Installing Apache Maven..."
      - wget -q https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz
      - mkdir -p /usr/local/maven
      - tar xzf apache-maven-3.9.6-bin.tar.gz -C /usr/local/maven
      - export M2_HOME=/usr/local/maven/apache-maven-3.9.6
      - export PATH=$M2_HOME/bin:$PATH
      
      # 3. Verify installations
      - echo "Verifying installations..."
      - java -version
      - mvn -v
      - echo "Environment setup complete"

  pre_build:
    commands:
      - echo "Cleaning previous build..."
      - mvn clean

  build:
    commands:
      - echo "Building project..."
      - mvn package

  post_build:
    commands:
      - echo "Build artifacts:"
      - ls -la target/
      - echo "Build completed successfully"

artifacts:
  files:
    - 'target/twig-*-core.jar'
  base-directory: '.'
