version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      # Install Maven explicitly
      - echo Installing Maven...
      - export MAVEN_VERSION=3.9.6
      - wget https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz -P /tmp
      - tar xf /tmp/apache-maven-${MAVEN_VERSION}-bin.tar.gz -C /opt
      - ln -s /opt/apache-maven-${MAVEN_VERSION} /opt/maven
      - export M2_HOME=/opt/maven
      - export MAVEN_HOME=/opt/maven
      - export PATH=${M2_HOME}/bin:${PATH}
      - echo Maven installed at $(which mvn)
      - mvn -v
      - java -version
      
  pre_build:
    commands:
      - echo Pre-build phase started...
      - echo $JAVA_HOME
      - echo PATH=$PATH
      - mvn -v
      
  build:
    commands:
      - echo Build started on `date`
      - mvn clean package
      
  post_build:
    commands:
      - echo Build completed on `date`
      
artifacts:
  files:
    - target/twig-0.0.4-core.jar
    - appspec.yml
    - scripts/**/*
    - pom.xml
  discard-paths: no
