version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "Installing Maven..."
      - wget https://archive.apache.org/dist/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.tar.gz
      - tar -xvf apache-maven-3.8.6-bin.tar.gz -C /opt
      - ln -s /opt/apache-maven-3.8.6 /opt/maven
      - export MAVEN_HOME=/opt/maven
      - export PATH=$PATH:$MAVEN_HOME/bin
      - mvn --version
  build:
    commands:
      - echo "Building the application..."
      - mvn clean package
  post_build:
    commands:
      - echo "Setting executable permissions on deployment scripts..."
      - chmod +x scripts/*.sh
      - echo "Packaging files into twig-0.0.4.zip..."
      - zip -r twig-0.0.4.zip appspec.yml scripts/ Dockerfile target/

artifacts:
  files:
    - twig-0.0.4.zip
  discard-paths: yes
