version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11 # Or another compatible JDK (e.g., openjdk17)
    commands:
      - echo "Installing Maven..."
      # Get the latest stable Maven version from the Apache Maven website
      - LATEST_MAVEN_VERSION=$(curl -s https://maven.apache.org/download.cgi | grep -oP 'maven-\d+\.\d+\.\d+-bin\.tar\.gz' | head -n 1 | sed 's/-bin\.tar\.gz//')
      - echo "Downloading Maven version: $LATEST_MAVEN_VERSION"
      - wget "https://dlcdn.apache.org/maven/maven-3/${LATEST_MAVEN_VERSION}/binaries/apache-maven-${LATEST_MAVEN_VERSION}-bin.tar.gz" -P /tmp
      - tar -xvf /tmp/apache-maven-${LATEST_MAVEN_VERSION}-bin.tar.gz -C /opt
      - ln -s /opt/apache-maven-${LATEST_MAVEN_VERSION} /opt/maven
      - export MAVEN_HOME=/opt/maven
      - export PATH=$PATH:$MAVEN_HOME/bin
      - echo "Maven and Java installed."
      - mvn --version # Verify installation
  build:
    commands:
      - echo "Build started on `date`"
      - echo "Compiling the Java code..."
      - mvn clean package
  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - target/*.war
    - appspec.yml
    - scripts/**/*
    - Dockerfile
  discard-paths: no
