version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - export JAVA_HOME=/usr/lib/jvm/java-17-amazon-corretto.x86_64
      - export PATH=$JAVA_HOME/bin:$PATH
      - java -version
      - mvn -v
  pre_build:
    commands:
      - mvn clean
  build:
    commands:
      - mvn package -Dmaven.compiler.release=17
  post_build:
    commands:
      - ls -la target/
      - echo "Build completed on $(date)"
artifacts:
  files:
    - 'target/twig-*-core.jar'
  base-directory: '.'
