version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo Installing dependencies
      - yum install -y git
      - curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m) > /usr/local/bin/docker-compose
      - chmod +x /usr/local/bin/docker-compose
  build:
    commands:
      - echo Building the Docker image
      - docker build -t mydockerhubusername/twig-tomcat .
  post_build:
    commands:
      - echo "Build complete"
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - docker push mydockerhubusername/twig-tomcat:latest

artifacts:
  files:
    - Dockerfile
    - target/twig-0.0.4.war
